before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: P/ac3+Afnr9RkK0JqfmLnBPUatvICXc9pZeQDa8Mux87LcyyemRTb9YoNKU/hEuSR/C6hhRfasixagfVMJgvfbhP0Dng9Aq3H1gJpL+/KR3vNAfDTv5M2x0RyJ94PT3sd/zhqcPEMeVrLpJ8dxh0h7woe/WPtwshJl4mONrZfTHLeGdng5PKjC0z3XY4+Ll6aMDS0vwe41IUWEiyHZF8kC3T5mOm913oQQ3jxsOV0r8daq1E2X7piM3MRSU+vGUViQueWNokyNXjIIBA2jkLVUYzRFyiP6bkWmTah541r3FRQJ7HepkLRSlXJgvT7mHSZRJ65zu4LlQYhdcqOPd1GhnvkxjRDdWe8vt2GMuLkAQxdo8X+xVyCaFK/MfnwOyyPOLev3geiJ9c6+iIUD9agqTFyrbm/lT/vrvOahj7p8AcaFXPgq+AReVO2tDef3BhKT4zB9/MY+4tCAaNWvegv+bosMR/AI5bhIqM835cgKi7BNfUnHQtFBmmclNLieCwPSZf1OEKKjp6zBgy/HkYxBlTWqoznLhColSxfOz1xVCt7yKBXFkGAEfh7SShImYzDDplXjOvWc79Tj9Zn46w7ZsuMk5CN7eklIq1/ahawQEPyH0AgxA1Qv5e9pvmUncquPmhNIA/AmvExGyJgV2YGXBfhtyBpN+c98IjazF6aGI= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
